<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ConsoleExample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OgXbox\OgXbox.csproj" />
  </ItemGroup>

</Project>
